### PR TITLE
Add fake nhs deductions

### PR DESCRIPTION
**Pull request by samcrang**
Create fake NHS deductions

These represent people who previously were on the NHS SPL but have been removed.

This is an additional file provided to us by the NHS.

The deductions and "normal" SPL files have the same columns:

```
$ diff -s <(cat ShieldedPatientsList_CabinetOffice_DailyLoad_20200519.csv | head -n1) <(cat ShieldedPatientsList_CabinetOffice_Deductions_20200520.csv |head -n1)
Files /dev/fd/11 and /dev/fd/12 are identical
```

### CODE REVIEW

**Comment by avisionh** [comment]
Just wondering, should this go into the `covid-engineering` repo?

https://github.com/alphagov/covid-engineering

**Comment by samcrang** [comment]
> Just wondering, should this go into the `covid-engineering` repo?
> 
> https://github.com/alphagov/covid-engineering

That would probably be sensible—we certainly end up copying the generated files from her into there anyway. How do you feel about that @nacnudus?

**Comment by nacnudus** [comment]
Good idea.

**Comment by nacnudus** [comment]
Although https://github.com/alphagov/covid-engineering is a private repo, whereas this is open, so maybe it should stay here.

**Pull request merged**
